# Generated by Django 4.0.4 on 2022-05-05 09:26

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(default=datetime.now),
            preserve_default=False,
        ),
    ]
