# Generated by Django 4.0.4 on 2022-05-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0002_product_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
