# Generated by Django 4.0.4 on 2022-05-06 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0003_remove_product_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bids',
            old_name='User',
            new_name='Bid_user',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.CharField(max_length=9999),
        ),
    ]
