# Generated by Django 4.0.4 on 2022-05-09 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0008_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('Street_name', models.CharField(max_length=255)),
                ('House_number', models.IntegerField()),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Zip', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_cardholder', models.CharField(max_length=255)),
                ('card_number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(16)])),
                ('Exp_month', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2)])),
                ('Exp_year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4)])),
            ],
        ),
    ]
