# Generated by Django 4.0.4 on 2022-05-11 10:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fire_sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0008_alter_product_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=255)),
                ('Street_name', models.CharField(max_length=255)),
                ('House_number', models.IntegerField()),
                ('City', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255)),
                ('Zip', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_of_cardholder', models.CharField(max_length=255)),
                ('card_number', models.CharField(max_length=16)),
                ('Exp_month', models.CharField(choices=[('01', 'JAN'), ('02', 'FEB'), ('03', 'MAR'), ('04', 'APR'), ('05', 'MAY'), ('06', 'JUN'), ('07', 'JUL'), ('08', 'AUG'), ('09', 'SEP'), ('10', 'OKT'), ('11', 'NOV'), ('12', 'DEC')], default='01', max_length=2)),
                ('Exp_year', models.IntegerField(validators=[fire_sale.models.check_exp_year])),
                ('CVC', models.IntegerField(validators=[fire_sale.models.check_cvc])),
            ],
        ),
        migrations.RemoveField(
            model_name='rating',
            name='Reviews',
        ),
        migrations.AddField(
            model_name='product',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rating',
            name='Grade',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_sale.product')),
            ],
        ),
    ]
