# Generated by Django 4.0.4 on 2022-05-09 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0009_contactinformation_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='CVC',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='Exp_month',
            field=models.CharField(choices=[('01', 'JAN'), ('02', 'FEB'), ('03', 'MAR'), ('04', 'APR'), ('05', 'MAY'), ('06', 'JUN'), ('07', 'JUL'), ('08', 'AUG'), ('09', 'SEP'), ('10', 'OKT'), ('11', 'NOV'), ('12', 'DEC')], default='01', max_length=2),
        ),
    ]
