# Generated by Django 4.0.4 on 2022-05-10 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0010_payment_cvc_alter_payment_exp_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payment',
            new_name='PaymentInformation',
        ),
        migrations.AddField(
            model_name='product',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='Zip',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_sale.product')),
            ],
        ),
    ]
