# Generated by Django 4.0.4 on 2022-05-10 14:40

import django.core.validators
from django.db import migrations, models
import fire_sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0010_payment_cvc_alter_payment_exp_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_cardholder', models.CharField(max_length=255)),
                ('card_number', models.IntegerField(validators=[fire_sale.models.credit_card_check])),
                ('exp_month', models.CharField(choices=[('01', 'JAN'), ('02', 'FEB'), ('03', 'MAR'), ('04', 'APR'), ('05', 'MAY'), ('06', 'JUN'), ('07', 'JUL'), ('08', 'AUG'), ('09', 'SEP'), ('10', 'OKT'), ('11', 'NOV'), ('12', 'DEC')], default='01', max_length=2)),
                ('exp_year', models.IntegerField(validators=[fire_sale.models.check_exp_year])),
                ('cvc', models.IntegerField(validators=[fire_sale.models.check_cvc])),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='House_number',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='Street_name',
            new_name='street_name',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='Zip',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='zip',
            field=models.IntegerField(default=105, validators=[django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
    ]
