# Generated by Django 4.0.4 on 2022-05-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0010_alter_rating_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
