# Generated by Django 4.0.4 on 2022-05-10 17:51

from django.db import migrations, models
import fire_sale.models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0011_paymentinformation_delete_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='city',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='full_name',
            new_name='Full_name',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='house_number',
            new_name='House_number',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='street_name',
            new_name='Street_name',
        ),
        migrations.RenameField(
            model_name='contactinformation',
            old_name='zip',
            new_name='Zip',
        ),
        migrations.RenameField(
            model_name='paymentinformation',
            old_name='cvc',
            new_name='CVC',
        ),
        migrations.RenameField(
            model_name='paymentinformation',
            old_name='exp_month',
            new_name='Exp_month',
        ),
        migrations.RenameField(
            model_name='paymentinformation',
            old_name='exp_year',
            new_name='Exp_year',
        ),
        migrations.RenameField(
            model_name='paymentinformation',
            old_name='name_of_cardholder',
            new_name='Name_of_cardholder',
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_number',
            field=models.BigIntegerField(validators=[fire_sale.models.credit_card_check]),
        ),
    ]
