# Generated by Django 4.0.4 on 2022-05-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0012_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
