# Generated by Django 4.0.4 on 2022-05-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0012_rename_city_contactinformation_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinformation',
            name='card_number',
            field=models.CharField(max_length=16),
        ),
    ]
