# Generated by Django 4.0.4 on 2022-05-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0011_rename_payment_paymentinformation_product_accepted_and_more'),
        ('fire_sale', '0013_alter_paymentinformation_card_number'),
    ]

    operations = [
    ]
