# Generated by Django 4.0.4 on 2022-05-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0031_categoryimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryImage',
        ),
    ]
