# Generated by Django 4.0.4 on 2022-05-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0032_delete_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.CharField(default=None, max_length=9999),
            preserve_default=False,
        ),
    ]
