# Generated by Django 4.0.4 on 2022-05-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0033_productcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='image',
        ),
    ]
