# Generated by Django 4.0.4 on 2022-05-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0034_remove_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.CharField(default=1, max_length=9999),
            preserve_default=False,
        ),
    ]
