# Generated by Django 4.0.4 on 2022-05-11 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0035_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fire_sale.product'),
            preserve_default=False,
        ),
    ]
