# Generated by Django 4.0.4 on 2022-05-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0036_rating_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
    ]
