# Generated by Django 4.0.4 on 2022-05-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0039_alter_rating_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('Pre Owned', 'Pre Owned')], default='NEW', max_length=20),
        ),
    ]
