# Generated by Django 4.0.4 on 2022-05-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0041_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='Zip',
            field=models.IntegerField(),
        ),
    ]
