# Generated by Django 4.0.4 on 2022-05-13 14:12

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0042_alter_contactinformation_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='Country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=9999),
        ),
    ]
