# Generated by Django 4.0.4 on 2022-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0045_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bidder',
            field=models.CharField(default=None, max_length=9999),
        ),
    ]
