# Generated by Django 4.0.4 on 2022-05-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0048_remove_product_highest_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='highest_bidder',
            field=models.CharField(max_length=9999, null=True),
        ),
    ]
