# Generated by Django 4.0.4 on 2022-05-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_sale', '0049_product_highest_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highest_bidder',
            field=models.IntegerField(max_length=9999, null=True),
        ),
    ]
